subscription_id    = "bfa5fa76-965d-497d-a2c3-300cd6dfb70b"
project_name       = "tstask"
environment        = "dev"
location           = "North Europe"
wordpress_hostname = "wb.ops-bewerbung-3.pg.senecops.com"
dns_zone_domain    = "ops-bewerbung-3.pg.senecops.com"
db_username        = "psqladmin"
db_password        = "H@Sh1CoR3!"