apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cluster_issuer_name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.tls_secret_name }}
    solvers:
    - http01:
        ingress:
          ingressClassName: {{ .Values.ingress_class_name }}